### ISSUE TITLE
Hope to add more file format support or configuration

### ISSUE THREAD

**Issue by FontEndArt** [Java-http/CSS-Modules-transform-vsc#3]
希望增加更多的文件格式支持或配置。
比如 ```.js```、 ```.ts```、```.tsx``` 等 或其他可配置的格式。

Hope to add more file format support or configuration.
For example, ```.js```, ```.ts```, ```.tsx``` etc. or other configurable formats.

**Comment by Java-http** [comment]
> 希望增加更多的文件格式支持或配置。
> 比如 `.js`、 `.ts`、`.tsx` 等 或其他可配置的格式。
> 
> Hope to add more file format support or configuration.
> For example, `.js`, `.ts`, `.tsx` etc. or other configurable formats.

你好，可以暂时修改当前文件的语言类型为 vue,html,react，目前插件支持这3种语言类型
